version: '3' # version of docker-compose

services:
  redis-server:
    image: 'redis'
  node-app:
    restart: on-failure
    build: .  # look inside current dir and build the Dockerfile
    ports:
      - '4001:8081'
